Refactor world select
matrix-org/thirdroom pull request #394
Opened 2022-10-07 10:07 UTC by ajbura

2022-10-14 02:38 UTC, robertlong requested changes

2022-10-14 02:53 UTC, robertlong commented
- Create World Dialog should wait for world to be created and then redirect so we don't have that weird state for `RoomBeingCreated`
- We should show the scene name and creator above the loading world progress bar

2022-10-14 15:25 UTC, ajbura commented on src/ui/App.tsx
> +const World = lazy(() => import("./views/session/world/World"));
Changed this to WorldRootView as we already have a WordView component (Used inside WorldRootView).

2022-10-14 15:29 UTC, ajbura commented on src/ui/hooks/useStore.ts
> +          state.world.disposeNetworkInterface?.();
creating network interface in mainThread hook with effect is not possible as network interface require groupCall which gets created outside mainThread and moving this inside mainThread hook will complicate error handling. 

So i just moved dispose network  interface call outside zustand store.

2022-10-17 17:45 UTC, robertlong commented
Looks great! As you said we need to address the mute state along with the connection reliability when joining while muted. We can do that in another PR

2022-10-17 17:49 UTC, robertlong approved these changes

2022-10-17 17:49 UTC, merged